users:
  - username: grafana
    password: n8RfaZ49P@9hYMf
    url_prefix: http://victoriametrics:8428

  - username: vmagent
    password: n8RfaZ49P@9hYMf
    url_prefix: http://victoriametrics:8428
