users:
  - username: grafana
    password: "%{VMAUTH_VMAGENT_PASSWORD}"
    url_prefix: http://victoriametrics:8428

  - username: vmagent
    password: "%{VMAUTH_GRAFANA_PASSWORD}"
    url_prefix: http://victoriametrics:8428
