# Generated by Django 5.2.17 on 2026-08-16 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cluster',
            name='created_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
