# Generated by Django 5.2.17 on 2026-08-18 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_cluster_created_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cluster',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='cluster',
            name='port',
        ),
        migrations.AddField(
            model_name='cluster',
            name='token',
            field=models.TextField(default=''),
        ),
    ]
