# Generated by Django 5.2.17 on 2026-08-21 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_namespace'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='namespace',
            constraint=models.UniqueConstraint(fields=('cluster', 'name'), name='unique_namespace_per_cluster'),
        ),
    ]
