# Generated by Django 6.1 on 2026-08-23 11:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_namespace_unique_namespace_per_cluster'),
    ]

    operations = [
        migrations.CreateModel(
            name='App',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('image', models.CharField(max_length=500)),
                ('replicas', models.PositiveIntegerField(default=1)),
                ('cpu', models.CharField(default='500m', max_length=50)),
                ('memory', models.CharField(default='512Mi', max_length=50)),
                ('namespace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='apps', to='api.namespace')),
            ],
        ),
    ]
