# Generated by Django 6.0.8 on 2026-09-04 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_backup'),
    ]

    operations = [
        migrations.AddField(
            model_name='cluster',
            name='ca_cert',
            field=models.TextField(blank=True, default=''),
        ),
    ]
