# Generated by Django 6.0.8 on 2026-09-04 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_cluster_ca_cert'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cluster',
            name='ca_cert',
        ),
        migrations.AlterField(
            model_name='cluster',
            name='token',
            field=models.TextField(),
        ),
    ]
